
from PyQt5 import QtCore, QtGui, QtWidgets
from filter import Filter
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Filter")
        MainWindow.resize(800, 613)
        MainWindow.setStyleSheet("font: 14pt \"MS Shell Dlg 2\";")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 190, 141, 41))
        self.label.setObjectName("label")
        self.threshold = QtWidgets.QTextEdit(self.centralwidget)
        self.threshold.setGeometry(QtCore.QRect(310, 190, 261, 41))
        self.threshold.setObjectName("threshold")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 20, 131, 41))
        self.label_2.setObjectName("label_2")
        self.input_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.input_folder.setGeometry(QtCore.QRect(310, 20, 461, 41))
        self.input_folder.setObjectName("input_folder")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 110, 261, 31))
        self.label_3.setObjectName("label_3")
        self.band_no = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.band_no.setGeometry(QtCore.QRect(310, 110, 91, 41))
        self.band_no.setObjectName("band_no")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(310, 80, 131, 31))
        self.label_4.setObjectName("label_4")
        self.output_folder = QtWidgets.QLineEdit(self.centralwidget)
        self.output_folder.setGeometry(QtCore.QRect(310, 260, 461, 41))
        self.output_folder.setText("")
        self.output_folder.setObjectName("output_folder")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 260, 151, 41))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 330, 151, 41))
        self.label_6.setObjectName("label_6")
        self.excel_sheet_name = QtWidgets.QLineEdit(self.centralwidget)
        self.excel_sheet_name.setGeometry(QtCore.QRect(310, 340, 461, 41))
        self.excel_sheet_name.setText("")
        self.excel_sheet_name.setObjectName("excel_sheet_name")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 410, 151, 41))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.start_btn = QtWidgets.QPushButton(self.centralwidget)
        self.start_btn.setGeometry(QtCore.QRect(320, 420, 161, 41))
        self.start_btn.setObjectName("start_btn")
        # self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        # self.progressBar.setGeometry(QtCore.QRect(120, 510, 621, 23))
        # self.progressBar.setProperty("value", 24)
        # self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 34))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Threshold"))
        self.label_2.setText(_translate("MainWindow", "Input Folder"))
        self.label_3.setText(_translate("MainWindow", "Which Band to apply?"))
        self.label_4.setText(_translate("MainWindow", "1,2,3,4"))
        self.label_5.setText(_translate("MainWindow", "Output Folder"))
        self.label_6.setText(_translate("MainWindow", "Excel Name"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.start_btn.clicked.connect(self.collect_data)
    def collect_data(self):
        print("inside")
        print(self.output_folder)
        output_folder = self.output_folder.text()
        print(output_folder)
        input_folder = self.input_folder.text()
        # band_no = int(self.band_no.text())
        # threshold = float(self.threshold.text())
        excel_name = self.excel_sheet_name.text()
        Filter(input_folder,excel_name = excel_name,  band_no=0, threshold=0, out_folder=0)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

